services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    depends_on:
      - action_server

  action_server:
    image: rasa/rasa-sdk:3.6.2
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
